apiVersion: apps/v1
kind: Deploymentttttt
metadata:
  name: guestbook-ui
  labels:
    key: val
    key_1: val2
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
